// Required by Webpack - do not touch
require.context('../', true, /\.(html|json|txt|dat)$/i)
require.context('../images/', true, /\.(gif|jpg|png|svg|eot|ttf|woff|woff2)$/i)
require.context('../stylesheets/', true, /\.(css|scss)$/i)

// First: Set up your name
let std_name = "Brendan Bates"
document.querySelector('#std_name').innerHTML = `<strong>${std_name}</strong>`
console.log("tester")
// [Spring 2024] - D3
import * as d3 from "d3";

// <svg width="500" height="600" style="background: rgb(232, 207, 207)" fill="transparent">d3.select('main')
let svg1 = d3.select('article').insert('svg')//.append('svg')
    .attr('width', 1100)
    .attr('height', 609)
    .style('background', '#eee')
    .style('fill', 'transparent')

let obj_icon2_0 = svg1.append('circle')
    .attr('cx', 190)
    .attr('cy', 70)
    .attr('r', 50)
    .attr('stroke', 'black')
    .attr('fill', '#6b1783')

// <circle cx="150" cy="125" r="100" stroke="black" fill="transparent" >
let obj_icon2_1 = svg1.append('ellipse')
    .attr('cx', 190)
    .attr('cy', 70)
    .attr('rx', 40)
    .attr('ry', 20)
    .attr('stroke', 'black')
    .attr('fill', 'white')

let obj_icon2_2 = svg1.append('circle')
    .attr('cx', 190)
    .attr('cy', 70)
    .attr('r', 15)
    .attr('stroke', 'black')
    .attr('fill', 'black')

// svg - animate
function animate_icon2_0()
{
    obj_icon2_1
        .transition()
        .duration(4000)
        .attr('ry', 0)
        .delay(3000)
        .transition()
        .duration(250)
        .attr('ry', 20)
        .transition()
        .duration(100)
        .attr('ry', 0)
        .transition()
        .duration(150)
        .attr('ry', 20)
        .on('end', animate_icon2_0)

    obj_icon2_2
        .transition()
        .duration(4000)
        .attr('r', 0)
        .delay(3000)
        .transition()
        .duration(250)
        .attr('r', 15)
        .transition()
        .duration(100)
        .attr('r', 0)
        .transition()
        .duration(150)
        .attr('r', 15)
        .transition()
        .duration(200)
        .attr('cx', 170)
        .delay(100)
        .transition()
        .duration(200)
        .attr('cx', 210)
        .delay(300)
        .transition()
        .duration(500)
        .attr('cx', 190)
        .on('end', animate_icon2_0)
}
animate_icon2_0()

let obj_icon1_2 = svg1.append('rect')
    .attr('x', 20)
    .attr('y', 20)
    .attr('width', 100)
    .attr('height', 100)
    .attr('stroke', 20)
    .attr('fill', '#000000')

let obj_icon1_1 = svg1.append('rect')
    .attr('x', 25)
    .attr('y', 25)
    .attr('width', 90)
    .attr('height', 90)
    .attr('stroke', 20)
    .attr('fill', '#EECD13FF')

let obj_icon1_0 = svg1.append('ellipse')
    .attr('cx', 70)
    .attr('cy', 70)
    .attr('rx', 30)
    .attr('ry', 8)
    .attr('stroke', 'black')
    .attr('fill', 'blue')
    //.attr('transform', 'rotate(45, 100, 150)')


function animate_icon1(){
    obj_icon1_0
        .transition()
        .attrTween('transform', function(d,i,a){return icon1_1_rotate})
        .duration(2000)
        .delay(100)
        .on('end', animate_icon1)

    obj_icon1_2
        .transition()
        .attrTween('transform', function(d,i,a){return ellipse_rotate})
        .duration(2000)
        .delay(100)
        .on('end', animate_icon1)
}
animate_icon1()
function animate_icon1_1(){
    obj_icon1_1
        .transition()
        .attrTween('transform', function(d,i,a){return ellipse_rotate})
        .duration(2100)
        .on('end', animate_icon1_1)
}
animate_icon1_1()

let obj_icon3_0 = svg1.append('rect')
    .attr('x', 260)
    .attr('y', 20)
    .attr('width', 100)
    .attr('height', 100)
    .attr('fill', '#000000')

let obj_icon3_1 = svg1.append('rect')
    .attr('x', 265)
    .attr('y', 25)
    .attr('width', 90)
    .attr('height', 90)
    .attr('fill', '#ffac05')

let obj_icon3_2 = svg1.append('circle')
    .attr('cx', 310)
    .attr('cy', 70)
    .attr('r', 5)
    .attr('fill', '#0056c7')

function animate_icon3(){
    obj_icon3_2
        .transition()
        .attr('cx', 310)
        .attr('cy', 100)
        .duration(1000)
        .transition()
        .attr('cy', 70)
        .attr('cx', 350)
        .duration(1000)
        .transition()
        .attr('cx', 310)
        .attr('cy', 40)
        .duration(1000)
        .transition()
        .attr('cy', 70)
        .attr('cx', 270)
        .duration(1000)
        .transition()
        .attr('cx', 310)
        .attr('cy', 70)
        .duration(1000)
        .transition()
        .attr('r', 40)
        .duration(1000)
        .transition()
        .attr('r',5)
        .duration(1000)
        .on('end', animate_icon3)

    obj_icon3_1
        .transition()
        .attr('height', 80)
        .attr('width', 80)
        .duration(1000)
        .transition()
        .attr('x', 275)
        .attr('y', 35)
        .duration(1000)
        .transition()
        .attr('x', 265)
        .duration(1000)
        .transition()
        .attr('y', 25)
        .duration(1000)
        .transition()
        .attr('height', 90)
        .attr('width', 90)
        .duration(3000)
        .on('end', animate_icon3)
}
animate_icon3()

let obj_icon4_0 = svg1.append('rect')
    .attr('x', 380)
    .attr('y', 20)
    .attr('width', 100)
    .attr('height', 100)
    .attr('stroke', 'black')
    .attr('fill', '#868181')

let obj_icon4_1 = svg1.append('rect')
    .attr('x', 385)
    .attr('y', 25)
    .attr('width', 90)
    .attr('height', 90)
    .attr('fill', '#83EEF0CE')


let obj_icon4_1_5 = svg1.append('rect')
    .attr('x', 385)
    .attr('y', 25)
    .attr('width', 90)
    .attr('height', 3)
    .attr('fill', '#000000')

let obj_icon4_2 = svg1.append('rect')
    .attr('x', 385)
    .attr('y', 25)
    .attr('width', 3)
    .attr('height', 90)
    .attr('fill', '#000000')

let obj_icon4_3 = svg1.append('rect')
    .attr('x', 432)
    .attr('y', 25)
    .attr('width', 5)
    .attr('height', 90)
    .attr('fill', '#000000')

let obj_icon4_4 = svg1.append('rect')
    .attr('x', 385)
    .attr('y', 72)
    .attr('width', 90)
    .attr('height', 5)
    .attr('fill', '#000000')

let obj_icon4_5 = svg1.append('rect')
    .attr('x', 430)
    .attr('y', 25)
    .attr('width', 5)
    .attr('height', 90)
    .attr('fill', '#868181')

let obj_icon4_6 = svg1.append('rect')
    .attr('x', 385)
    .attr('y', 70)
    .attr('width', 90)
    .attr('height', 5)
    .attr('fill', '#868181')

function animate_icon4(){
    obj_icon4_1
        .transition()
        .attr('fill', '#FFA200FF')
        .duration(5000)
        .transition()
        .attr('fill', '#3b3b78')
        .duration(5000)
        .transition()
        .attr('fill', '#83EEF0CE')
        .duration(5000)
        .on('end', animate_icon4)
}
animate_icon4()

let obj_icon5_0 = svg1.append('rect')
    .attr('x', 20)
    .attr('y', 150)
    .attr('width', 100)
    .attr('height', 100)
    .attr('stroke', 'black')
    .attr('fill', '#000000')

let obj_icon5_line1 = svg1.append('line')
    .attr('x1', 30)
    .attr('y1', 160)
    .attr('x2', 40)
    .attr('y2', 160)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_line2 = svg1.append('line')
    .attr('x1', 30)
    .attr('y1', 160)
    .attr('x2', 30)
    .attr('y2', 170)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_line3 = svg1.append('line')
    .attr('x1', 30)
    .attr('y1', 170)
    .attr('x2', 40)
    .attr('y2', 170)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_line4 = svg1.append('line')
    .attr('x1', 40)
    .attr('y1', 170)
    .attr('x2', 40)
    .attr('y2', 180)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_line5 = svg1.append('line')
    .attr('x1', 40)
    .attr('y1', 180)
    .attr('x2', 30)
    .attr('y2', 180)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_H1 = svg1.append('line')
    .attr('x1', 45)
    .attr('y1', 160)
    .attr('x2', 45)
    .attr('y2', 180)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_H2 = svg1.append('line')
    .attr('x1', 55)
    .attr('y1', 160)
    .attr('x2', 55)
    .attr('y2', 180)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_H3 = svg1.append('line')
    .attr('x1', 45)
    .attr('y1', 170)
    .attr('x2', 55)
    .attr('y2', 170)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_I1 = svg1.append('line')
    .attr('x1', 60)
    .attr('y1', 160)
    .attr('x2', 60)
    .attr('y2', 165)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_I2 = svg1.append('line')
    .attr('x1', 60)
    .attr('y1', 170)
    .attr('x2', 60)
    .attr('y2', 180)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_T1 = svg1.append('line')
    .attr('x1', 77)
    .attr('y1', 160)
    .attr('x2', 69)
    .attr('y2', 180)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_T2 = svg1.append('line')
    .attr('x1', 65)
    .attr('y1', 168)
    .attr('x2', 79)
    .attr('y2', 168)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_P1 = svg1.append('line')
    .attr('x1', 30)
    .attr('y1', 185)
    .attr('x2', 30)
    .attr('y2', 240)
    .attr('stroke', 'black')
    .attr('stroke-width', 10)

let obj_icon5_P2 = svg1.append('line')
    .attr('x1', 30)
    .attr('y1', 200)
    .attr('x2', 50)
    .attr('y2', 200)
    .attr('stroke', 'black')
    .attr('stroke-width', 30)

let obj_icon5_O = svg1.append('circle')
    .attr('cx', 50)
    .attr('cy', 230)
    .attr('r', 10)
    .attr('fill', '#0056C7FF')//0056C7FF

let obj_icon5_st1 = svg1.append('line')
    .attr('x1', 65)
    .attr('y1', 200)
    .attr('x2', 75)
    .attr('y2', 200)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_st2 = svg1.append('line')
    .attr('x1', 65)
    .attr('y1', 200)
    .attr('x2', 65)
    .attr('y2', 210)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_st3 = svg1.append('line')
    .attr('x1', 65)
    .attr('y1', 210)
    .attr('x2', 75)
    .attr('y2', 210)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_st4 = svg1.append('line')
    .attr('x1', 75)
    .attr('y1', 210)
    .attr('x2', 75)
    .attr('y2', 220)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_st5 = svg1.append('line')
    .attr('x1', 65)
    .attr('y1', 220)
    .attr('x2', 75)
    .attr('y2', 220)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_st6 = svg1.append('line')
    .attr('x1', 85)
    .attr('y1', 220)
    .attr('x2', 85)
    .attr('y2', 240)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

let obj_icon5_st7 = svg1.append('line')
    .attr('x1', 70)
    .attr('y1', 230)
    .attr('x2', 100)
    .attr('y2', 225)
    .attr('stroke', 'black')
    .attr('stroke-width', 3)

function animate_icon5(){
    obj_icon5_I1
        .transition()
        .attr('y1', 165)
        .attr('y2', 170)
        .duration(1000)
        .transition()
        .attr('y1', 155)
        .attr('y2', 160)
        .duration(1000)
        .on('end', animate_icon5)

    obj_icon5_T1
        .transition()
        .attr('x1', 73)
        .duration(1000)
        .transition()
        .attr('x1', 63)
        .duration(1000)
        .on('end', animate_icon5)

    obj_icon5_0
        .transition()
        .attr('fill','#5d4200')
        .duration(5000)
        .on('end', animate_icon5)
}

animate_icon5()

//let dayandnight = d3.interpolateString('fill(\'#83EEF0CE\')','fill(\'#FFA200FF\')','fill(\'#27273DFF\')')
let icon1_1_rotate = d3.interpolateString('rotate(360, 70, 70)','rotate(0, 70, 70)')
let ellipse_rotate = d3.interpolateString('rotate(0, 70, 70)','rotate(360, 70, 70)')
let interpol_rotate = d3.interpolateString('rotate(0, 125, 150)', 'rotate(360, 125, 150)')
